package cerr

const (
	SUCCESS      = 0
	UNKNOWN      = 1
	BAD_REQUEST  = 400
	UNAUTHORIZED = 401
	SYSTEM_ERROR = 500

	ERROR_USER_NOT_EXIST       = 1001
	ERROR_USER_ALREADY_EXIST   = 1002
	ERROR_USER_PASSWORD_WRONG  = 1003
	ERROR_USER_TOKEN_INVALIDE  = 1004
	ERROR_USER_TOKEN_EXPIRE    = 1005
	ERROR_USER_TOKEN_NOT_MATCH = 1006

	ERROR_ARTICLE_TAG_NOT_EXIST      = 2001
	ERROR_ARTICLE_CATEGORY_NOT_EXIST = 2002
	ERROR_ARTICLE_NOT_EXIST          = 2003
	ERROR_ARTICLE_TYPE_NOT_SUPPORT   = 2004
	ERROR_ARTICLE_CATEGORY_EXIST     = 2005
	ERROR_ARTICLE_TAG_EXIST          = 2006
)

var codeMsg = map[int]string{
	SUCCESS:      "SUCCESS",
	UNKNOWN:      "未知错误",
	BAD_REQUEST:  "请求参数错误",
	UNAUTHORIZED: "未认证错误",
	SYSTEM_ERROR: "系统内部错误",

	ERROR_USER_NOT_EXIST:       "用户不存在",
	ERROR_USER_ALREADY_EXIST:   "用户已存在",
	ERROR_USER_PASSWORD_WRONG:  "密码错误",
	ERROR_USER_TOKEN_INVALIDE:  "Token无效",
	ERROR_USER_TOKEN_EXPIRE:    "登陆过期",
	ERROR_USER_TOKEN_NOT_MATCH: "Token不匹配",

	ERROR_ARTICLE_TAG_NOT_EXIST:      "标签不存在",
	ERROR_ARTICLE_TAG_EXIST:          "标签已存在",
	ERROR_ARTICLE_CATEGORY_NOT_EXIST: "分类不存在",
	ERROR_ARTICLE_CATEGORY_EXIST:     "分类已存在",
	ERROR_ARTICLE_NOT_EXIST:          "文章不存在",
	ERROR_ARTICLE_TYPE_NOT_SUPPORT:   "不支持的文章类型",
}

func GetMessage(code int) string {
	if msg, ok := codeMsg[code]; ok {
		return msg
	}
	return codeMsg[UNKNOWN]
}
